### ISSUE TITLE
Nature Shader 2022 Overlay Material disabled in Distant Trees

### ISSUE THREAD

**Issue by krazyxiii** [visualdesigncafe/nature-shaders#15]
**Describe the bug**
Nature Shader Overlay feature is disabled at a distance.

**To Reproduce**
1. Setup Unity project, setup Nature Renderer, Nature Shader, Terrain Tools
2. Create a Terrain and Add some Nature Shader with Overlay configured Trees
3. Zoom away from the trees
4. After some distance, the Nature Shader Overlay rendering is no longer applied. See screenshot

**Expected behavior**
I would expect the Overlay applied still be visible

**Screenshots**
![image](https://github.com/visualdesigncafe/nature-shaders/assets/73378334/06782c13-74c9-46c4-96ab-2af0392273e3)

**Project(please complete the following information):**
 - Unity version: [e.g. 2022.3.2f1
 - Render Pipeline: URP
 - Render Pipeline Version : 14.08
 - Nature Shaders Version : 2022

**System (please complete the following information):**
 - Platform: Windows
 - Platform OS: Windows 10
 - Graphics API and Version Direct X12

**Additional context**

**Comment by maxplooi** [comment]
You can adjust the quality settings via a C# script to increase the distance, the default is 512 units. Overlays are rendered into a texture, which has a limited resolution/size and thus are not visible past a certain distance. To increase the distance, either increase the resolution or decrease the accuracy. Please see the [documentation](https://visualdesigncafe.com/nature-shaders/docs/2022/quality-settings) for more details.

Example:
```c#
using VisualDesignCafe.Nature;

QualitySettings.Overlay.Resolution = 4096;
```

**Comment by krazyxiii** [comment]
As per Max, issue was in the QualitySettings which I had missed. This was not an issue to begin with. Thanks for the support.
